# Generated by Django 5.2 on 2025-04-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_categoria_descripcion_categoria_abreviacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='abreviacion',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
