# Generated by Django 5.2 on 2025-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
