# Generated by Django 5.2 on 2025-04-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_unidad_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unidad',
        ),
        migrations.AddField(
            model_name='material',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='factor_conversion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='materiales_compra', to='inventario.unidad'),
        ),
        migrations.AddField(
            model_name='material',
            name='unidad_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='materiales_venta', to='inventario.unidad'),
        ),
    ]
