# Generated by Django 5.2 on 2025-05-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_material_descripcion_remove_material_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
    ]
