# Generated by Django 5.2 on 2025-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_detalleventa_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendidoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=100)),
                ('total_vendido', models.IntegerField()),
                ('tipo', models.CharField(choices=[('más vendido', 'Más Vendido'), ('menos vendido', 'Menos Vendido')], max_length=13)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteVentaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('nombre_material', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('gerente', 'Gerente'), ('empleado', 'Empleado')], max_length=8)),
            ],
        ),
    ]
