# Generated by Django 5.2 on 2025-05-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_notificacion_productovendidosemanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='material',
            field=models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='inventario.material'),
        ),
    ]
