from .material import Material
from .categoria import Categoria
from .proveedor import Proveedor
from .unidad import Unidad
from .descuento import Descuento
from .devolucion import Devolucion
from .venta import Venta
from .productovendidosemanal import ProductoVendidoSemanal
from .notificacion import Notificacion
from .reporteventasemanal import ReporteVentaSemanal
from .usuario import Usuario
from .notificacion import Notificacion